### ISSUE TITLE
Pipeline of renalysis move search engines to SearchGUI. 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/nf-workflows#7]
The current way of injecting the parameters to the reanalysis pipeline is by hard-coding and re-write manually the parameters file for each search engine.It would be great if we use a general parameters file for SearchGUI. 

- [x] Replace msgfplus and XTandem by SearchGUI providing a global param file. 
- [x] Evaluate if is possible to replace xTandem with another search engine like comet or tide.

**Comment by ypriverol** [comment]
We probalby need to search which version of XTandem + MSGF+ SearchgUI is using.

**Comment by ypriverol** [comment]
@jgriss I will try to move the current pipeline from comet -> tide because comet is not yet supported in  PIA.

**Comment by jgriss** [comment]
@ypriverol Perfectly fine with me! If you prefer, I'm happy to do this as well.

**Comment by jgriss** [comment]
Due to the bugs in PeptideShaker this has been abandoned
